# -*- coding: utf-8 -*-
"""PHSAM2_T-S-L_Malak1/24/2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Djyz_pq-aqLMrVXFGRnngZu8witYlwSR
"""

!pip install -q ripser persim

# Commented out IPython magic to ensure Python compatibility.
# --- First, make sure you have SAM installed ---
!git clone https://github.com/facebookresearch/sam2.git
# %cd ./sam2/
!pip install -q -e .
!pip install ultralytics

import sam2
print(sam2.__file__)

import os, json, csv, random, time
import cv2
import numpy as np
import torch

from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("DEVICE:", DEVICE)

# --- DATA PATHS ---
ORIG_IMAGE_DIR = "/content/knee_xray_images"
GT_DIR         = "/content/JsonMasks"
CENTROIDS_JSON = "/content/centroids_ph.json"  # You must already have this from the PHSAM1 code

# --- OUTPUT ROOT ---
OUT_ROOT = "/content/phase1_phsam2_results"
os.makedirs(OUT_ROOT, exist_ok=True)

# Load centroids
with open(CENTROIDS_JSON, "r") as f:
    centroids = json.load(f)

print("Loaded centroids:", len(centroids))

# crop ratios
TOP_RATIO = 0.15
BOTTOM_RATIO = 0.15
LEFT_RATIO = 0.10
RIGHT_RATIO = 0.10

def map_centroids_to_original(img_gray, c1, c2):
    """
    c1 = centroid from non-flipped crop
    c2 = centroid from vertically flipped crop
    map both to original image coordinates
    """
    h, w = img_gray.shape[:2]
    top    = int(h * TOP_RATIO)
    bottom = int(h * (1 - BOTTOM_RATIO))
    left   = int(w * LEFT_RATIO)
    right  = int(w * (1 - RIGHT_RATIO))
    crop_h = bottom - top

    x1o = left + int(c1[0])
    y1o = top  + int(c1[1])

    y2_unflipped = (crop_h - 1) - int(c2[1])
    x2o = left + int(c2[0])
    y2o = top  + y2_unflipped

    x1o = np.clip(x1o, 0, w-1); y1o = np.clip(y1o, 0, h-1)
    x2o = np.clip(x2o, 0, w-1); y2o = np.clip(y2o, 0, h-1)
    return (int(x1o), int(y1o)), (int(x2o), int(y2o))

def dice_score_bin(pred_mask_bin, gt_mask_bin):
    a = pred_mask_bin.astype(bool)
    b = gt_mask_bin.astype(bool)
    inter = np.logical_and(a, b).sum()
    denom = a.sum() + b.sum()
    return 1.0 if denom == 0 else (2.0 * inter / (denom + 1e-8))

def find_gt_path(base_id, original_filename):
    exts = [".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"]

    # 1) exact same filename first
    candidate = os.path.join(GT_DIR, original_filename)
    if os.path.exists(candidate):
        return candidate

    # 2) base + _mask.<ext>
    for e in exts:
        candidate = os.path.join(GT_DIR, f"{base_id}_mask{e}")
        if os.path.exists(candidate):
            return candidate

    # 3) base + any ext
    for e in exts:
        candidate = os.path.join(GT_DIR, f"{base_id}{e}")
        if os.path.exists(candidate):
            return candidate

    return None

def load_sam2_predictor(model_cfg: str, checkpoint_path: str):
    sam2_model = build_sam2(model_cfg, checkpoint_path, device=DEVICE)
    predictor = SAM2ImagePredictor(sam2_model)
    return predictor

def segment_sam2_on_original(predictor, image_bgr, p1, p2, mask_index:int):
    """
    predictor.set_image expects BGR in your notebook — keep consistent.
    returns (mask_bin 0/1, mask_img 0/255)
    """
    predictor.set_image(image_bgr)
    pts = np.array([p1, p2], dtype=np.float32)
    labels = np.array([1, 1], dtype=np.int32)

    masks, scores, logits = predictor.predict(
        point_coords=pts,
        point_labels=labels,
        multimask_output=True
    )  # masks: [K,H,W]

    masks = np.asarray(masks)
    if masks.dtype != np.bool_:
        masks = masks > 0.5

    if masks.shape[0] == 0:
        raise RuntimeError("SAM2 returned zero masks")

    # pad to at least 3 masks (some configs can return <3)
    K = masks.shape[0]
    if K < 3:
        masks = np.concatenate([masks, np.repeat(masks[-1][None,...], 3-K, axis=0)], axis=0)

    if mask_index >= masks.shape[0]:
        raise RuntimeError(f"Requested mask_index={mask_index} but got K={masks.shape[0]} masks")

    chosen = masks[mask_index]
    mask_bin = chosen.astype(np.uint8)
    mask_img = (mask_bin * 255).astype(np.uint8)
    return mask_bin, mask_img

SAMPLE_SIZE = 63
SEED = 777  # seed
random.seed(SEED)
np.random.seed(SEED)

exclude_set = set()
old_csv = "/content/phase1_phsam1_results/vit_h_mask0_seed42/phase1_vit_h_mask0_seed42.csv"
if os.path.exists(old_csv):
    import pandas as pd
    old_df = pd.read_csv(old_csv)
    exclude_set = set(old_df["filename"].dropna().tolist())
    print("Excluding PH-SAM1 images:", len(exclude_set))
else:
    print("Old PH-SAM1 batch not found — will sample randomly.")

eligible = []
for filename, c_list in centroids.items():
    if filename in exclude_set:
        continue
    if not isinstance(c_list, (list, tuple)) or len(c_list) < 2:
        continue
    img_path = os.path.join(ORIG_IMAGE_DIR, filename)
    if not os.path.exists(img_path):
        continue
    base_id = os.path.splitext(filename)[0]
    gt_path = find_gt_path(base_id, filename)
    if gt_path is None or not os.path.exists(gt_path):
        continue
    eligible.append(filename)

print("Eligible images:", len(eligible))
if len(eligible) < SAMPLE_SIZE:
    raise ValueError(f"Not enough eligible images for sample. eligible={len(eligible)} need={SAMPLE_SIZE}")

sampled_files = random.sample(eligible, SAMPLE_SIZE)
print("Sampled:", len(sampled_files))
print("First 5:", sampled_files[:5])

PHSAM2_MODELS = {
    "sam2_tiny": {
        "cfg": "configs/sam2.1/sam2.1_hiera_t.yaml",
        "ckpt": "/content/drive/MyDrive/YoloDART/sam2.1_hiera_tiny.pt",
        "mask_idx": 2
    },
    "sam2_small": {
        "cfg": "configs/sam2.1/sam2.1_hiera_s.yaml",
        "ckpt": "/content/drive/MyDrive/YoloDART/sam2.1_hiera_small.pt",
        "mask_idx": 1
    },
    "sam2_large": {
        "cfg": "configs/sam2.1/sam2.1_hiera_l.yaml",
        "ckpt": "/content/drive/MyDrive/YoloDART/sam2.1_hiera_large.pt",
        "mask_idx": 2
    },
}

def run_phase1_phsam2_one_model(model_key, cfg, sampled_files, save_masks=True):
    model_out_dir = os.path.join(OUT_ROOT, f"{model_key}_mask{cfg['mask_idx']}_seed{SEED}")
    os.makedirs(model_out_dir, exist_ok=True)

    print(f"\n=== Running {model_key} (mask {cfg['mask_idx']}) ===")
    predictor = load_sam2_predictor(cfg["cfg"], cfg["ckpt"])

    rows = []
    dice_list = []
    time_list = []

    t_batch0 = time.time()

    for filename in sampled_files:
        img_path = os.path.join(ORIG_IMAGE_DIR, filename)
        base_id = os.path.splitext(filename)[0]
        gt_path = find_gt_path(base_id, filename)

        # read image
        image_bgr = cv2.imread(img_path, cv2.IMREAD_COLOR)
        if image_bgr is None:
            continue
        g_gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

        # centroids (crop coords)
        c1 = tuple(map(int, centroids[filename][0]))
        c2 = tuple(map(int, centroids[filename][1]))
        p1, p2 = map_centroids_to_original(g_gray, c1, c2)

        # SAM2 inference + timing
        t0 = time.time()
        pred_bin, pred_img = segment_sam2_on_original(
            predictor, image_bgr, p1, p2, mask_index=cfg["mask_idx"]
        )
        t1 = time.time()
        dt = t1 - t0

        # load GT bin
        gt = cv2.imread(gt_path, cv2.IMREAD_UNCHANGED)
        if gt is None:
            continue
        if gt.ndim == 3:
            gt_bin = (np.sum(gt, axis=2) > 0).astype(np.uint8)
        else:
            gt_bin = (gt > 0).astype(np.uint8)

        # resize GT if needed
        if gt_bin.shape != pred_bin.shape:
            gt_bin = cv2.resize(gt_bin, (pred_bin.shape[1], pred_bin.shape[0]), interpolation=cv2.INTER_NEAREST)

        d = dice_score_bin(pred_bin, gt_bin)

        dice_list.append(d)
        time_list.append(dt)

        pred_name = ""
        if save_masks:
            pred_name = f"{base_id}_pred_{model_key}_mask{cfg['mask_idx']}_dice{d:.4f}.png"
            cv2.imwrite(os.path.join(model_out_dir, pred_name), pred_img)

        rows.append({
            "filename": filename,
            "id": base_id,
            "gt_file": os.path.basename(gt_path),
            "dice": float(d),
            "time_sec": float(dt),
            "pred_mask_file": pred_name
        })

    t_batch1 = time.time()
    batch_time = t_batch1 - t_batch0

    avg_dice = float(np.mean(dice_list)) if dice_list else 0.0
    best_dice = float(np.max(dice_list)) if dice_list else 0.0
    avg_time = float(np.mean(time_list)) if time_list else 0.0

    # Per-image CSV
    per_csv = os.path.join(model_out_dir, f"phase1_{model_key}_mask{cfg['mask_idx']}_seed{SEED}.csv")
    with open(per_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["filename","id","gt_file","dice","time_sec","pred_mask_file"])
        for r in rows:
            w.writerow([r["filename"], r["id"], r["gt_file"],
                        f"{r['dice']:.6f}", f"{r['time_sec']:.6f}", r["pred_mask_file"]])
        w.writerow([])
        w.writerow(["SUMMARY","","","","",""])
        w.writerow(["avg_dice", avg_dice])
        w.writerow(["best_dice", best_dice])
        w.writerow(["avg_time_per_image_sec", avg_time])
        w.writerow(["total_batch_time_sec", float(batch_time)])
        w.writerow(["n_images_used", len(rows)])

    summary = {
        "model": model_key,
        "mask_index": cfg["mask_idx"],
        "seed": SEED,
        "n_images_used": len(rows),
        "avg_dice": avg_dice,
        "best_dice": best_dice,
        "avg_time_per_image_sec": avg_time,
        "total_batch_time_sec": float(batch_time),
        "csv_path": per_csv,
        "out_dir": model_out_dir
    }

    print("DONE:", summary)
    return summary

# run all 3 models
all_summaries = []
for k, cfg in PHSAM2_MODELS.items():
    all_summaries.append(run_phase1_phsam2_one_model(k, cfg, sampled_files, save_masks=True))

# combined summary csv
summary_csv = os.path.join(OUT_ROOT, f"PHASE1_PHSAM2_SUMMARY_seed{SEED}.csv")
with open(summary_csv, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["model","mask_index","avg_dice","best_dice","avg_time_per_image_sec","total_batch_time_sec","n_images_used","csv_path"])
    for s in all_summaries:
        w.writerow([s["model"], s["mask_index"],
                    f"{s['avg_dice']:.6f}", f"{s['best_dice']:.6f}",
                    f"{s['avg_time_per_image_sec']:.6f}", f"{s['total_batch_time_sec']:.6f}",
                    s["n_images_used"], s["csv_path"]])

print("\n Combined summary saved to:", summary_csv)

"""PHSAM 2 PHASE 2"""

import pandas as pd

paths_phsam2 = {
    "SAM2-Tiny":  "/content/phase1_phsam2_results/sam2_tiny_mask2_seed777/phase1_sam2_tiny_mask2_seed777.csv",
    "SAM2-Small": "/content/phase1_phsam2_results/sam2_small_mask1_seed777/phase1_sam2_small_mask1_seed777.csv",
    "SAM2-Large": "/content/phase1_phsam2_results/sam2_large_mask2_seed777/phase1_sam2_large_mask2_seed777.csv",
}

dfs_phsam2 = {}
for k, p in paths_phsam2.items():
    df = pd.read_csv(p)
    df = df[pd.to_numeric(df["dice"], errors="coerce").notnull()]
    dfs_phsam2[k] = df

for k, df in dfs_phsam2.items():
    print(k, "images:", len(df))

import matplotlib.pyplot as plt

metrics = {
    "Dice": "dice",
    "Precision": "precision",
    "Recall": "recall",
    "F1-score": "f1"
}

for title, col in metrics.items():
    data = [dfs_phsam2[k][col].astype(float) for k in dfs_phsam2]
    labels = list(dfs_phsam2.keys())

    plt.figure(figsize=(7,5))
    plt.boxplot(data, labels=labels, showfliers=True)
    plt.title(f"PH-SAM2 {title} Distribution (63 Images)")
    plt.ylabel(title)
    plt.grid(True, alpha=0.3)
    plt.show()

import os
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

GT_DIR   = "/content/JsonMasks"
OUT_ROOT = "/content/phase1_phsam2_results"

PHSAM2_RUNS = {
    "SAM2-Tiny": {
        "csv": f"{OUT_ROOT}/sam2_tiny_mask2_seed777/phase1_sam2_tiny_mask2_seed777.csv",
        "pred_dir": f"{OUT_ROOT}/sam2_tiny_mask2_seed777",
    },
    "SAM2-Small": {
        "csv": f"{OUT_ROOT}/sam2_small_mask1_seed777/phase1_sam2_small_mask1_seed777.csv",
        "pred_dir": f"{OUT_ROOT}/sam2_small_mask1_seed777",
    },
    "SAM2-Large": {
        "csv": f"{OUT_ROOT}/sam2_large_mask2_seed777/phase1_sam2_large_mask2_seed777.csv",
        "pred_dir": f"{OUT_ROOT}/sam2_large_mask2_seed777",
    },
}

# quick check
for k,v in PHSAM2_RUNS.items():
    print(k, "csv exists?", os.path.exists(v["csv"]), "| pred_dir exists?", os.path.exists(v["pred_dir"]))

def find_gt_path(base_id, original_filename):
    exts = [".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"]

    candidate = os.path.join(GT_DIR, original_filename)
    if os.path.exists(candidate):
        return candidate

    for e in exts:
        candidate = os.path.join(GT_DIR, f"{base_id}_mask{e}")
        if os.path.exists(candidate):
            return candidate

    for e in exts:
        candidate = os.path.join(GT_DIR, f"{base_id}{e}")
        if os.path.exists(candidate):
            return candidate

    return None

def load_mask_as_bin(path):
    m = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if m is None:
        return None
    if m.ndim == 3:
        m = (np.sum(m, axis=2) > 0).astype(np.uint8)
    else:
        m = (m > 0).astype(np.uint8)
    return m

def confusion_counts(pred_bin, gt_bin):
    # ensure boolean
    p = pred_bin.astype(bool)
    g = gt_bin.astype(bool)
    tp = np.logical_and(p, g).sum()
    fp = np.logical_and(p, ~g).sum()
    fn = np.logical_and(~p, g).sum()
    tn = np.logical_and(~p, ~g).sum()
    return tn, fp, fn, tp

def prec_rec_f1_from_counts(fp, fn, tp):
    precision = tp / (tp + fp + 1e-8)
    recall    = tp / (tp + fn + 1e-8)
    f1        = 2 * precision * recall / (precision + recall + 1e-8)
    return float(precision), float(recall), float(f1)

PHASE2_SUMMARIES = {}

for model_name, info in PHSAM2_RUNS.items():
    df = pd.read_csv(info["csv"])

    df = df[df["filename"].notnull()].copy()
    df = df[~df["filename"].astype(str).str.contains("SUMMARY", case=False, na=False)]

    # If your CSV accidentally contains trailing non-data rows, dice may become NaN;
    if "dice" in df.columns:
        df["dice"] = pd.to_numeric(df["dice"], errors="coerce")

    # Prepare new columns
    df["tn"] = 0
    df["fp"] = 0
    df["fn"] = 0
    df["tp"] = 0
    df["precision"] = np.nan
    df["recall"]    = np.nan
    df["f1"]        = np.nan

    agg_tn = agg_fp = agg_fn = agg_tp = 0
    used = 0

    for idx, row in df.iterrows():
        filename = str(row["filename"])
        base_id = os.path.splitext(filename)[0]

        gt_path = find_gt_path(base_id, filename)
        if gt_path is None:
            continue

        pred_file = str(row.get("pred_mask_file", "")).strip()
        if pred_file == "" or pred_file.lower() == "nan":
            continue

        pred_path = os.path.join(info["pred_dir"], pred_file)

        gt_bin = load_mask_as_bin(gt_path)
        pred_bin = load_mask_as_bin(pred_path)

        if gt_bin is None or pred_bin is None:
            continue

        # resize GT to pred if needed
        if gt_bin.shape != pred_bin.shape:
            gt_bin = cv2.resize(gt_bin, (pred_bin.shape[1], pred_bin.shape[0]), interpolation=cv2.INTER_NEAREST)

        tn, fp, fn, tp = confusion_counts(pred_bin, gt_bin)
        precision, recall, f1 = prec_rec_f1_from_counts(fp, fn, tp)

        df.at[idx, "tn"] = int(tn)
        df.at[idx, "fp"] = int(fp)
        df.at[idx, "fn"] = int(fn)
        df.at[idx, "tp"] = int(tp)
        df.at[idx, "precision"] = precision
        df.at[idx, "recall"] = recall
        df.at[idx, "f1"] = f1

        agg_tn += tn; agg_fp += fp; agg_fn += fn; agg_tp += tp
        used += 1

    # Overall metrics from aggregated confusion
    overall_precision, overall_recall, overall_f1 = prec_rec_f1_from_counts(agg_fp, agg_fn, agg_tp)
    confusion = np.array([[agg_tn, agg_fp],
                          [agg_fn, agg_tp]], dtype=np.int64)

    print(f"\n=== {model_name} (63 images expected) ===")
    print("Images used:", used)
    print(f"Pixel Precision: {overall_precision:.4f}")
    print(f"Pixel Recall:    {overall_recall:.4f}")
    print(f"Pixel F1:        {overall_f1:.4f}")
    print("Confusion Matrix [ [TN FP], [FN TP] ]:")
    print(confusion)

    # Save updated CSV (phase2)
    out_csv = os.path.join(info["pred_dir"], f"phase2_{model_name.replace('-','_').lower()}_seed777.csv")
    df.to_csv(out_csv, index=False)
    print("Saved PHASE2 per-image CSV ->", out_csv)

    PHASE2_SUMMARIES[model_name] = {
        "images_used": used,
        "precision": overall_precision,
        "recall": overall_recall,
        "f1": overall_f1,
        "tn": int(agg_tn), "fp": int(agg_fp), "fn": int(agg_fn), "tp": int(agg_tp),
        "phase2_csv": out_csv
    }

import pandas as pd
import matplotlib.pyplot as plt

phase2_csvs = {
    "SAM2-Tiny":  "/content/phase1_phsam2_results/sam2_tiny_mask2_seed777/phase2_sam2_tiny_seed777.csv",
    "SAM2-Small": "/content/phase1_phsam2_results/sam2_small_mask1_seed777/phase2_sam2_small_seed777.csv",
    "SAM2-Large": "/content/phase1_phsam2_results/sam2_large_mask2_seed777/phase2_sam2_large_seed777.csv",
}

dfs2 = {}
for name, path in phase2_csvs.items():
    df = pd.read_csv(path)
    df = df[df["filename"].notnull()].copy()
    # numeric conversion
    for c in ["dice","precision","recall","f1","time_sec"]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
    df = df[df["precision"].notnull()]  # phase2 rows only
    dfs2[name] = df
    print(name, "rows:", len(df))

import os
PLOT_DIR = "/content/phase2_phsam2_plots"
os.makedirs(PLOT_DIR, exist_ok=True)

def make_boxplot(metric, title, ylabel, filename):
    data = [dfs2[k][metric].astype(float) for k in dfs2]
    labels = list(dfs2.keys())

    plt.figure(figsize=(7,5))
    plt.boxplot(data, labels=labels, showfliers=True)
    plt.title(title)
    plt.ylabel(ylabel)
    plt.grid(True, alpha=0.3)
    out_path = os.path.join(PLOT_DIR, filename)
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.show()
    print("Saved:", out_path)

# Dice (if present)
if "dice" in next(iter(dfs2.values())).columns:
    make_boxplot("dice", "PH-SAM2 Dice Distribution (63 Images)", "Dice", "boxplot_dice_phsam2.png")

make_boxplot("precision", "PH-SAM2 Pixel Precision Distribution (63 Images)", "Precision", "boxplot_precision_phsam2.png")
make_boxplot("recall",    "PH-SAM2 Pixel Recall Distribution (63 Images)", "Recall",    "boxplot_recall_phsam2.png")
make_boxplot("f1",        "PH-SAM2 Pixel F1 Distribution (63 Images)", "F1",          "boxplot_f1_phsam2.png")

summary = []
for model, df in dfs2.items():
    # aggregate confusion from per-image counts if they exist
    has_counts = all(c in df.columns for c in ["tn","fp","fn","tp"])
    if has_counts:
        TN = int(df["tn"].sum()); FP = int(df["fp"].sum())
        FN = int(df["fn"].sum()); TP = int(df["tp"].sum())
        precision = TP/(TP+FP+1e-8)
        recall    = TP/(TP+FN+1e-8)
        f1        = 2*precision*recall/(precision+recall+1e-8)
    else:
        TN=FP=FN=TP=None
        precision = df["precision"].mean()
        recall    = df["recall"].mean()
        f1        = df["f1"].mean()

    summary.append({
        "model": model,
        "n_images": len(df),
        "pixel_precision": float(precision),
        "pixel_recall": float(recall),
        "pixel_f1": float(f1),
        "TN": TN, "FP": FP, "FN": FN, "TP": TP,
        "avg_dice": float(df["dice"].mean()) if "dice" in df.columns else None,
        "avg_time_sec": float(df["time_sec"].mean()) if "time_sec" in df.columns else None
    })

df_sum = pd.DataFrame(summary)
out_csv = "/content/phase1_phsam2_results/PHASE2_PHSAM2_SUMMARY_seed777.csv"
df_sum.to_csv(out_csv, index=False)

print("✅ Saved:", out_csv)
df_sum
